name: Enjin Minecraft Plugin
main: com.enjin.officialplugin.EnjinMinecraftPlugin
version: 2.3.1
website: www.enjin.com
author: www.Enjin.com
description: A plugin which allows the enjin servers to communicate with your server.
softdepend: [Vault]
commands:
  enjinkey:
    description: Sets the enjin online key to the specified string.
    usage: Usage /enjinkey pass123
    aliases: [ek]
  enjin:
    description: General enjin commands
    usage: Usage /enjin report
    aliases: [e]
permissions:
  enjin.setkey:
    description: Allows the player to set the key for the plugin.
    default: op
  enjin.report:
    description: Allows the player to generate a report for submitting to enjin.
    default: op
  enjin.debug:
    description: Turns debugging on and off for this session.
    default: op