name: Enjin Minecraft Plugin
main: com.enjin.officialplugin.EnjinMinecraftPlugin
version: 2.1.6
website: www.enjin.com
author: www.Enjin.com
description: A plugin which allows the enjin servers to communicate with your server.
softdepend: [Vault]
commands:
  enjinkey:
    description: Sets the enjin online key to the specified string.
    usage: Usage /enjinkey pass123
    aliases: [ek]
