name: EnjinMinecraftPlugin
main: com.enjin.bukkit.EnjinMinecraftPlugin
version: ${version}${platform}
website: www.enjin.com
author: www.Enjin.com
description: A plugin which allows the enjin servers to communicate with your server.
softdepend: [Vault,Votifier,NuVotifier,mcMMO,Essentials,VanishNoPacket,PermissionsEx,GroupManager,BPermissions,ZPermissions,PermissionsBukkit]
commands:
  enjinkey:
    description: Sets the enjin online key to the specified string.
    aliases: [ek]
  enjin:
    description: General enjin commands
    aliases: [e]
permissions:
  enjin.setkey:
    description: Allows the player to set the key for the plugin.
    default: op
  enjin.report:
    description: Allows the player to generate a report for submitting to enjin.
    default: op
  enjin.debug:
    description: Turns debugging on and off for this session.
    default: op
  enjin.push:
    description: Pushes all ranks from server to enjin.
    default: op
  enjin.updateheads:
    description: Forces an update on all the stat signs and heads in the game.
    default: op
  enjin.lag:
    description: Allows the player to access the lag report on the server.
    default: op
  enjin.notify.*:
    default: op
    description: Enables all notifications.
    children:
      enjin.notify.connectionstatus: true
      enjin.notify.update: true
      enjin.notify.failedupdate: true
      enjin.notify.invalidauthkey: true
      enjin.notify.permissionsnotworking: true
      enjin.notify.votifiererrored: true
      enjin.notify.econoutdated: true
      enjin.notify.mcmmooutdated: true
  enjin.sign:
    default: op
    description: Allows the player to make and remove stat signs and heads.
    children:
      enjin.sign.set: true
      enjin.sign.remove: true
  enjin.sign.remove:
    description: Allows the player to remove stat signs and heads.
    default: op
  enjin.sign.set:
    description: Allows the player to create stat signs and heads.
    default: op
  enjin.notify.connectionstatus:
    description: Let's the player know if the plugin's connection status changes.
    default: op
  enjin.notify.update:
    description: Receive notifications upon login if the plugin has been updated.
    default: op
  enjin.notify.failedupdate:
    description: Receive notifications upon login if the plugin has failed to update.
    default: op
  enjin.notify.invalidauthkey:
    description: Receive notification if the auth key is invalid.
    default: op
  enjin.notify.permissionsnotworking:
    description: Receive notification if the permissions plugin isn't working correctly.
    default: op
  enjin.notify.votifiererrored:
    description: Receive notification if Votifier isn't working correctly.
    default: op
  enjin.notify.econoutdated:
    description: Receive notification if your economy plugin isn't updated for Vault 1.4.1.
    default: op
  enjin.notify.mcmmooutdated:
    description: Receive notification if your mcMMO plugin is older than what we support.
    default: op
  enjin.points.add:
    description: Add points to a player.
    default: op
  enjin.points.remove:
    description: Remove points to a player.
    default: op
  enjin.points.set:
    description: Set points on a player.
    default: op
  enjin.points.getothers:
    description: Allows the player to see the points value of other players.
    default: op
  enjin.points.getself:
    description: Allows the player to see how many points they have.
    default: true
  enjin.tags.view:
    description: Allows the player to see the tags of other players.
    default: op
  enjin.support:
    description: Allows the player submit a support ticket.
    default: op
  enjin.ticket:
    description: Allows the player to view their own tickets.
    default: op
  enjin.ticket.private:
    description: Allows the player to view private messages.
    default: op
  enjin.ticket.open:
    description: Allows the player to view open tickets.
    default: op
  enjin.ticket.reply:
    description: Allows the player to reply to tickets.
    default: op
  enjin.ticket.status:
    description: Allows the player to set the status of tickets.
    default: op
  enjin.test.vote:
    description: Allows the player to add votes manually.
    default: op