name: EnjinMinecraftPlugin
main: com.enjin.bungee.EnjinMinecraftPlugin
version: ${version}-bungee
author: www.Enjin.com
description: A plugin which allows the enjin servers to communicate with your proxy server.